---
title: "Segmentation: Clustering"
author: 
  - Elizabeth Olsen
  - Luis Francisco Gomez
date: 2024-11-27
format: 
  html:
    toc: true
    number-sections: true
    code-fold: true
    embed-resources: true
editor: visual
---

```{r}
#| label: libraries
#| message: false

library(tidyverse)
library(skimr)
library(cluster)
library(DT)
```

# Import data

```{r}
#| message: false

segmentation <- read_csv(file = "../000_data/005_data_chapter5.csv")
```

# Transform data

```{r}
segmentation <- segmentation |> 
  mutate(gender  = factor(x = gender, 
                          ordered = FALSE),
         kids    = as.integer(x = kids),
         ownHome = factor(x = ownHome, 
                          ordered = FALSE),
         subscribe = factor(x = subscribe,
                            ordered = FALSE),
         Segment = factor(x = Segment,
                          ordered = FALSE))
```

# Summary statistics

```{r}
segmentation |> 
  skim()
```

# Distances

## Euclidean

```{r}
segmentation_dist_euclidean <- segmentation |> 
  select(age, kids) |> 
  daisy(metric = "euclidean") |> 
  as.matrix() |> 
  as_tibble()

segmentation_dist_euclidean |> 
  select(`1`:`5`) |> 
  slice(1:5) |> 
  mutate(customer = 1:5, 
         .before = `1`) |> 
  datatable() |> 
  formatRound(columns = c("1", "2", "3", "4", "5"),
              digits = 4)
```

## Gower

```{r}
segmentation_dist_gower <- segmentation |> 
  daisy(metric = "gower") |> 
  as.matrix() |> 
  as_tibble()


segmentation_dist_gower |> 
  select(`1`:`5`) |>
  slice(1:5) |> 
  mutate(customer = 1:5, 
         .before = `1`) |> 
  datatable() |> 
  formatRound(columns = c("1", "2", "3", "4", "5"),
              digits = 4)
```
