---
title: "Comparing groups: tables and visualizations"
author: 
  - Norah Jones
  - Bill Gates
  - Luis Francisco
format: 
  html:
    embed-resources: true
    toc: true
    number-sections: true
    code-fold: true
editor: visual
---

```{r}
#| label: libraries
#| message: false

library(tidyverse)
library(skimr)
library(DT)
```

# Import

```{r}
#| message: false

segmentation <- read_csv(file = "../000_data/005_data_chapter5.csv")
```

# Transform

```{r}
segmentation <- segmentation |> 
  mutate(gender = factor(x = gender, ordered = FALSE),
         kids = as.integer(x = kids),
         ownHome = factor(x = ownHome, ordered = FALSE),
         subscribe = factor(x = subscribe, ordered = FALSE),
         Segment = factor(x = Segment, ordered = FALSE))
```

# Summary statistics

```{r}
segmentation |> 
  skim()
```

# Descriptive statistics by group

## Mean income

```{r}
#| message: false

income_by_segment_ownhome <- segmentation |> 
  group_by(Segment, ownHome) |> 
  summarise(mean_income = mean(income)) |> 
  ungroup()

income_by_segment_ownhome |> 
  datatable(colnames = c("Own Home" = "ownHome",
                         "Mean Income" = "mean_income")) |> 
  formatRound(columns = "Mean Income", 
              digits = 2)
```

## Number of kids

```{r}
#| message: false

sum_kids_by_segment_ownhome <- segmentation |> 
  group_by(Segment, ownHome) |> 
  summarise(sum_kids = sum(kids))

sum_kids_by_segment_ownhome |> 
  datatable(colnames = c("Own Home" = "ownHome",
                         "Total kids" = "sum_kids"))
```

# Visualization

## Behavior of subscribers by segment

```{r}
pct_customers_subscribe <- segmentation |> 
  count(subscribe, Segment) |> 
  group_by(Segment) |> 
  mutate(pct_subscribers = (n / sum(n))*100) |> 
  ungroup() |> 
  filter(subscribe == "subYes") |> 
  mutate(Segment = fct_reorder(.f = Segment, 
                               .x = pct_subscribers))
  
pct_customers_subscribe |> 
  ggplot() +
  geom_col(aes(x = pct_subscribers,
               y = Segment)) +
  labs(x = "Percentage of subscribers",
       title = "Percentage of subscribers by segment")
```
