---
title: "Analysis Satisfaction data"
author: 
  - Maria Alberto
  - Maria Obando
  - Luis Parra
format: 
  html:
    embed-resources: true
    toc: true
    number-sections: true
    code-fold: true
editor: visual
---

```{r}
#| message: false

# Libraries -----
library(tidyverse)
library(skimr)
library(DT)
```

# Import

This is a data set about the satisfaction of different aspects in relation to some consumers

```{r}
#| message: false

satisfaction_data <- read_csv(file = "../000_data/002_data_chapter2.csv")
```

# Transforming data

```{r}
satisfaction_data <- satisfaction_data |> 
  mutate(Segment = factor(x = Segment, ordered = FALSE))

satisfaction_data |> 
  datatable()
```

# Summary statistics

```{r}
satisfaction_data |> 
  skim()
```

## Calculating the mean and the median

```{r}
mean_median_iprodsat <- satisfaction_data |> 
  summarise(mean_iprodsat = mean(x = iProdSAT), 
            median_iprodsat = median(x = iProdSAT))

mean_median_iprodsat |> 
  datatable()
```

## Analyzing data step by step

```{r}
group_by_mean <- satisfaction_data |> 
  group_by(Segment) |> 
  summarise(mean_iprodsat = mean(iProdSAT), 
            mean_isalessat = mean(iSalesSAT))

group_by_mean |> 
  datatable()
```


