---
title: "Specific instructions: marketing report part 3"
execute: 
  echo: true
  warning: false
format: 
  html:
    number-sections: true
    toc: true
    embed-resources: true
    css: ../000_css/styles.css
bibliography: ../000_references/marketing_research_and_analytics.bib
editor: source
---

# Marketing report structure part 3

In this third report you are going to use data from `bike_sales` as a third step to complete the 2 tasks by:

-   Estimating an statistical linear model to determine the price of a new product not offer by the company with information of the products the corporation already offer to support the Research and Development (R & D) division

-   Build a customer segmentation model by grouping the bike shops into clusters to support the marketing team

Use the template `003_marketing_report_part-3.qmd` to build the marketing report. You can find the template to use in 2 locations. Choose the option of your preference:

-   <https://github.com/luifrancgom/marketing_research_and_analytics/> \> 000_templates \> 003_marketing_report_part-3.qmd

-   Tercer Corte 40% \> Learning Resources \> Support material \> Templates \> 003_marketing_report_part-3.qmd