---
title: "Identifying drivers of outcomes: linear models"
author:
  - Norah Jones
  - Bill Gates
  - Luis Francisco Gomez
format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    embed-resources: true
---

```{r}
#| label: load-r-libraries
#| message: false
#| warning: false
library(tidyverse)
library(skimr)
library(corrr)
library(tidymodels)
library(performance)
library(DT)
```

# Introduction


# Import data 

```{r}
#| message: false
amusement_park <- read_csv(
  file = "../000_data/007_data_set_chapter-7.csv"
)
```

# Transform

```{r}
# Transform data ----
amusement_park <- amusement_park |> 
  mutate(
    weekend = factor(x = weekend, ordered = FALSE),
    num.child = as.integer(x = num.child),
    logdist = log(x = distance, base = exp(1))
  )
```

# Summarize data 

```{r}
amusement_park |>
  skim()
```

# Correlation

## Visualization 

```{r}
#| message: false
#| warning: false
correlation_matrix <- amusement_park |> 
  select(num.child, rides:logdist) |> 
  correlate()

correlation_matrix |> 
  autoplot(
    triangular = "lower"
  )
```

# Linear models

## Visualization

```{r}
#| message: false
amusement_park |> 
  ggplot(
    aes(x = rides, y = overall)
  ) + 
  geom_point() +
  geom_smooth(
    method = "lm",
    se = FALSE,
    color = "blue"
  ) +
  labs(
    x = "Satisfaction with rides",
    y = "Overall satisfaction"
  )
```

## Estimation


```{r}
model1 <- lm(
  formula = overall ~ rides,
  data = amusement_park
)
```

```{r}
#| label: tbl-model2
#| tbl-cap: Model 2 summary 
model2 <- lm(
  formula = overall ~ rides + games + wait + clean,
  data = amusement_park
)

model2_tidy <- model2 |> 
  tidy()

model2_tidy <- model2 |> 
  tidy()

model2_tidy |> 
  datatable(
    colnames = c(
      "Term",
      "Estimation",
      "Standard error",
      "T-statistic",
      "P-value"
    )
  ) |> 
  formatRound(
    columns = c(2, 3, 4, 5)
  )
```

### Checking model

```{r}
#| label: fig-check-model-model1
#| fig-cap: Checking assumptions model 1
#| fig-height: 10
check_model(model1)
```

```{r}
#| label: fig-check-model-model2
#| fig-cap: Checking assumptions model 2
#| fig-height: 10
check_model(model2)
```

## Predictions

```{r}
#| label: tbl-model2-new-data-pred
#| tbl-cap: Model prediction using data for 2 hypothetical clients for rides, games, wait and clean score
new_data <- tibble(
  rides = c(30, 70),
  games = c(10, 80),
  wait  = c(57, 60),
  clean = c(90, 93)
)

model2_new_data_pred <- predict(
  object = model2,
  newdata = new_data
) |> 
  enframe(
    name = "observation",
    value = "overall_pred"
  ) |> 
  bind_cols(new_data)

model2_new_data_pred |> 
  datatable(
    colnames = c(
      "Observation",
      "Overall prediction",
      "Rides",
      "Games",
      "Wait",
      "Clean"
    )
  ) |> 
  formatRound(
    columns = c(2),
    digits = 2
  )
```