---
title: "Comparing groups: tables and visualizations"
format: 
  html:
    embed-resources: true
    toc: true
editor: visual
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(skimr)
```

# Importing data

```{r}
#| message: false
segmentation <- read_csv(file = "http://goo.gl/qw303p")
```

# Transform data

```{r}
segmentation <- segmentation |>
  mutate(gender = factor(gender, ordered = FALSE),
         kids = as.integer(kids),
         ownHome = factor(ownHome, ordered = FALSE),
         subscribe = factor(subscribe, ordered = FALSE),
         Segment = factor(Segment, ordered = FALSE))
```

# Explore data

```{r}
segmentation |> skim()
```

# Percentage of subscribers by `Segment` and `ownHome`

## Prepare data

```{r}
subscriber_by_segment_home_ownership <- segmentation |> 
  count(subscribe, Segment, ownHome) |> 
  group_by(Segment, ownHome) |> 
  mutate(percentage_n = (n / sum(n)) * 100) |> 
  ungroup()

subscriber_by_segment_home_ownership
```

# Visualize data

```{r}
subscriber_by_segment_home_ownership |> 
  ggplot() + 
  geom_col(aes(x = subscribe, y = percentage_n)) +
  facet_wrap(facets = vars(Segment, ownHome),
             nrow = 2, ncol = 4)
```
