---
title: "Reducing data complexity"
author: 
  - Penelope Cruz
  - Luis Francisco Gomez
date: 2024-11-20
format: 
  html:
    embed-resources: true
    toc: true
    number-sections: true
    code-fold: true
editor: visual
---

```{r}
#| message: false
#| label: libraries

library(tidyverse)
library(skimr)
library(corrr)
library(DT)
library(tidyheatmaps)
```

# Import data

```{r}
#| message: false

consumer_brand <- read_csv(file = "../000_data/008_data_chapter8.csv")

```

# Transform data

```{r}
consumer_brand_scale <- consumer_brand |> 
  mutate(across(.cols =  perform:rebuy, 
                .fns  = ~ scale(x = .x,
                                center = TRUE,
                                scale  = TRUE)[,1]))
```

# Summary statistics

```{r}
consumer_brand_scale |> 
  skim()
```

# Correlation matrix

```{r}
#| message: false

correlation_matrix <- consumer_brand_scale |> 
  # How to select continuous columns
  select(perform:rebuy) |> 
  correlate(use = "pairwise.complete.obs", 
            method = "pearson",
            diagonal = NA)

correlation_matrix |> 
  datatable() |> 
  formatRound(columns = names(correlation_matrix)[2:10],
              digits = 2)
```

## Visualization data

```{r}
correlation_matrix |> 
  autoplot(triangular = "lower", 
           method = "HC")
```

# Reducing data complexity

## Using means and heatmaps

### Prepare data

```{r}
brand_mean <- consumer_brand_scale |> 
  group_by(brand) |> 
  summarise(across(.cols = everything(),
                   .fns  = mean))

## Prepare data ----
brand_mean_longer <- brand_mean |> 
  pivot_longer(cols = perform:rebuy, 
               names_to = "perceptual_adjectives", 
               values_to = "value_mean") |> 
  mutate(brand = fct_reorder(.f = brand, 
                             .x = value_mean),
         perceptual_adjectives = fct_reorder(.f = perceptual_adjectives,
                                             .x = value_mean))
```

### Visualize data

```{r}
brand_mean_longer |> 
  tidyheatmap(rows = brand,
              columns = perceptual_adjectives,
              values = value_mean, 
              cluster_rows = TRUE,
              cluster_cols = TRUE,
              clustering_method = "complete", 
              display_numbers = TRUE, 
              border_color = "black", 
              fontsize = 12)
```
