---
title: "Describing data"
format: 
  html:
    embed-resources: true
    code-fold: true
editor: visual
---

```{r}
#| message: false
library(tidyverse)
library(skimr)
```

# Importing data

```{r}
#| message: false
url <- "http://goo.gl/QPDdMl"
weekly_stores <- read_csv(file = url)
```

# Transforming data

```{r}
weekly_stores <- weekly_stores |> 
  mutate(storeNum = factor(x = storeNum, 
                           ordered = FALSE),
         Year = factor(x = Year,
                       ordered = TRUE),
         Week = factor(x = Week, ordered = TRUE),
         p1prom = as.logical(x = p1prom),
         p2prom = as.logical(x = p2prom))
```

# Visualization

```{r}
weekly_stores |> 
  ggplot() +
  geom_histogram(aes(x = p1sales, y = after_stat(density)),
                 color = "black", fill="lightblue",
                 bins = 30) +
  geom_density(aes(x = p1sales),
               color = "darkred", 
               linetype = "solid",
               linewidth = 1) +
  scale_x_continuous(breaks = seq(from = 60, to = 300, by = 20)) +
  labs(x = "Sales of product 1 (units)",
       y = "Density",
       title = "Product 1: Distribution of sales in all stores")
```
