---
title: "Identifying drivers of outcomes: linear models"
author: 
  - Bill Gates
  - Norah Jones
  - Luis Francisco Gomez
format: 
  html:
    embed-resources: true
    toc: true
    number-sections: true
    code-fold: true
editor: visual
---

```{r}
#| label: libraries
#| message: false

library(tidyverse)
library(skimr)
library(corrr)
library(DT)
library(tidymodels)
```

# Import

```{r}
#| message: false

amusement_park <- read_csv(file = "../000_data/007_data_chapter7.csv")
```

# Transform

```{r}
# Transform ----
amusement_park <- amusement_park |> 
  mutate(weekend = factor(x = weekend, 
                          ordered = FALSE),
         num.child = as.integer(x = num.child)) |> 
  mutate(logdist = log(x = distance))
```

# Summary statistics

```{r}
amusement_park |> 
  skim()
```

## Correlation

```{r}
#| label: tbl-correlation-matrix
#| tbl-cap: "Correlation matrix"
#| message: false

## Correlation ----
correlation_matrix <- amusement_park |> 
  select(where(is.numeric), -c(distance)) |> 
  correlate(method = "pearson", 
            use = "pairwise.complete.obs")

correlation_matrix |> 
  datatable()
```

```{r}
#| label: fig-correlation-matrix-heatmap
#| fig-cap: "Heatmap: correlation matrix"

correlation_matrix |> 
  autoplot(triangular = "lower")
```

# Modeling: linear models

## Model 1

```{r}
### Model 1 ----
model1 <- lm(formula = overall ~ rides,
             data = amusement_park)

model1_tidy <- model1 |> 
  tidy()

model1_tidy |> 
  datatable()
```

```{r}
par(mfrow = c(2,2))
plot(model1)
par(mfrow = c(1,1))
```
