---
title: "Identifying Drivers of Outcomes: Linear Models"
author: 
  - Ana de Armas
  - Luis Francisco Gomez
date: 2024-11-13
format: 
  html:
    embed-resources: true
    code-fold: true
    toc: true
    number-sections: true
editor: visual
---

```{r}
#| label: libraries
#| message: false

library(tidyverse)
library(skimr)
library(corrr)
library(tidymodels)
library(DT)
library(coefplot)
```

# Import data

```{r}
#| message: false

amusement_park <- read_csv(file = "../000_data/007_data_chapter7.csv") |> 
  mutate(weekend   = factor(x = weekend, ordered = FALSE),
         num.child = as.integer(x = num.child),
         logdist   = log(x = distance))
```

# Summarize data

```{r}
amusement_park |> 
  skim()
```

# Correlation

```{r}
#| message: false

correlation_matrix <- amusement_park |> 
  select(where(fn = is.numeric)) |> 
  correlate()

correlation_matrix |> 
  autoplot(triangular = "lower")
```

# Data visualization

```{r}
#| message: false

amusement_park |> 
  ggplot(aes(x = rides, y = overall)) +
  geom_point() +
              # lm: linear model
  geom_smooth(method = "lm", 
              se = FALSE,
              color = "red") + 
  labs(x = "Satisfaction with rides",
       y = "Overall satisfaction",
       title = "Linear model between satisfaction with rides and overall satisfaction")
```

# Modeling

```{r}
#| message: false

model1 <- lm(formula = overall ~ rides, 
             data = amusement_park)

model1_tidy <- model1 |> tidy()

model1_tidy |> 
  datatable() |> 
  formatRound(c("estimate", 
                "std.error",
                "statistic",
                "p.value"), 
              digits = 3) 
```

## Coefficients

```{r}
coef <- model1_tidy |> 
  select(estimate)

coef$estimate[1]
coef$estimate[2]
```

## Forecast

### A result that make sense

```{r}
coef$estimate[1] + coef$estimate[2]*95
```

### A result that doesn't make sense

```{r}
coef$estimate[1] + coef$estimate[2]*50
```

## Linear models with multiple variables

```{r}
model2 <- lm(formula = overall ~ rides + games + wait + clean,
             data = amusement_park)

model2_tidy <- model2 |> 
  tidy()

model2_tidy |> 
  datatable() |> 
  formatRound(columns = c("estimate",
                          "std.error",
                          "statistic",
                          "p.value"),
              digits = 4)
```

### Visualizing t-test

```{r}
coefplot(model = model2,
         intercept = FALSE,
         lwdOuter = 1.5)
```

### Predicting with multiple variables

```{r}
new_data <- tibble(rides = c(30, 70),
                   games = c(10, 80),
                   wait  = c(57, 60),
                   clean = c(90, 93))

prediction <- predict(object = model2,
        newdata = new_data) |> 
  enframe(name = "observation",
          value = "overall_predict") |> 
  bind_cols(new_data)

prediction |> 
  datatable() |> 
  formatRound(columns = c("overall_predict"),
              digits = 2)
```

