---
title: "Relationships between continuous variables"
format: 
  html:
    embed-resources: true
    toc: true
    number-sections: true
    code-fold: true
editor: visual
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(skimr)
library(corrr)
```

# Import data

```{r}
#| message: false
# customer <- read_csv(file = "000_data/004_data_chapter4.csv")
customer <- read_csv(file = "http://goo.gl/PmPkaG")
```

# Explore data

```{r}
customer |> glimpse()
```

# Transform data 1

```{r}
customer <- customer |>
  mutate(cust.id = factor(x = cust.id, ordered = FALSE),
         email = factor(x = email, ordered = FALSE),
         online.visits = as.integer(x = online.visits),
         online.trans = as.integer(x = online.trans),
         store.trans = as.integer(x = store.trans),
         sat.service = factor(x = sat.service, ordered = TRUE),
         sat.selection = factor(x = sat.selection, ordered = TRUE))
```

# Describe data

```{r}
customer |> skim()
```

# Data visualization

## Spending: online vs physical store

```{r}
ggplot(customer) +
  geom_histogram(aes(x = store.spend),
                 color = "black")
```

```{r}
ggplot(customer) +
  geom_point(aes(x = store.spend, y = online.spend,
                 color = email)) +
                     # See hex codes for colors
  scale_color_manual(values = c("red",  "#33ffe9")) +
  scale_x_continuous(breaks = c(1, 2, 5, 10, 20, 50, 100, 500),
                     transform = "log1p") +
  scale_y_continuous(breaks = c(1, 5, 50, 500),
                     transform = "log1p") +
  labs(x = "Spending in the physical store (dollars)",
       y = "Spending online (dollars)",
       title = "Spending in the physical store vs online",
       color = "Email")
```

## Age vs the credit score

```{r}
ggplot(customer) +
  geom_point(aes(x = age, y = credit.score))
```

# Pearson correlation

```{r}
cor(x = customer$age, y = customer$credit.score,
    method = "pearson")
```

## Matrix correlation

```{r}
correlation_matrix <- customer |> 
  select(where(is.numeric)) |> 
  correlate(use = "pairwise.complete.obs")

correlation_matrix |> 
  autoplot(triangular = "lower")
```

# Transform data 2

## Spending in the physical store

```{r}
customer |>
  # We apply this transformation
  # because store.spend includes
  # 0 values
  mutate(log_store.spend = log(store.spend + 1)) |> 
  ggplot() +
  geom_histogram(aes(x = log_store.spend),
                 color = "black",
                 bins = 30)
```

## Distance to the store

```{r}
customer |>
  ggplot() +
  geom_histogram(aes(x = distance.to.store),
                 color = "black",
                 bins = 30) +
  scale_x_continuous(transform = "log")
```

### Improve correlation

#### Case 1

```{r}
cor(x = customer$store.spend, 
    y = customer$distance.to.store)
```

#### Case 2

```{r}
cor(x = customer$store.spend,
    y = 1 / customer$distance.to.store)
```

#### Case 3

```{r}
cor(x = customer$store.spend,
    y = 1 / sqrt(customer$distance.to.store))
```

```{r}
customer |> 
  mutate(distance.to.store_trans2 = 1 / sqrt(distance.to.store)) |> 
  ggplot() +
  geom_point(aes(x = distance.to.store_trans2, 
                 y = store.spend))
```

# Visualizing categorical values

## Alternative 1

```{r}
customer |> 
  ggplot() +
  geom_point(aes(x = sat.service, y = sat.selection),
             position = position_jitter(width = 0.2,
                                        height = 0.2))
```

## Alternative 2

```{r}
customer |> 
  count(sat.service, sat.selection) |> 
  ggplot() +
  ## Check out 
  ## https://ggplot2.tidyverse.org/reference/geom_text.html
  geom_text(aes(x = sat.service, y = sat.selection,
                label = n))
```

## Alternative 3

```{r}
customer |> 
  count(sat.service, sat.selection) |> 
  ggplot() +
  ## Check out 
  ## https://ggplot2.tidyverse.org/reference/geom_tile.html
  geom_tile(aes(x = sat.service, y = sat.selection,
                fill = n),
            color = "black") +
  ## Check out 
  ## https://ggplot2.tidyverse.org/reference/scale_gradient.html
  scale_fill_gradient2()
```