---
title: "Relationships Between Continuous Variables"
author: 
  - Bill Gates
  - Norah Jones
  - Francisco
format: 
  html:
    embed-resources: true
    toc: true
    number-sections: true
    code-fold: true
editor: visual
---

```{r}
#| label: libraries
#| message: false

library(tidyverse)
library(skimr)
library(corrr)
library(DT)
```

# Import

```{r}
#| message: false

customer <- read_csv(file = "../000_data/004_data_chapter4.csv")
```

# Transform

```{r}
customer <- customer |> 
  mutate(cust.id = factor(x = cust.id, ordered = FALSE),
         email = factor(x = email, ordered = FALSE),
         online.visits = as.integer(x = online.visits),
         online.trans = as.integer(x = online.trans),
         store.trans = as.integer(x = store.trans),
         sat.service = factor(x = sat.service, 
                              ordered = TRUE),
         sat.selection = factor(x = sat.selection, 
                                ordered = TRUE))
```

# Summarize

```{r}
customer |> 
  select(-c(cust.id)) |> 
  skim()
```

# Visualization

## Spending

```{r}
customer |> 
  ggplot() + 
  geom_point(aes(x = online.spend,
                 y = store.spend,
                 color = email)) +
  scale_color_manual(values = c("#8e0c14", "#2c98af"),
                     labels = c("No", "Yes")) +
  labs(x = "Amount spend online yearly (US dollars)",
       y = "Amount spend in the physical store (US dollars)",
       color = "Email",
       title = "Spend online vs physical store by customer")
```

## Satisfaction

```{r}
customer |> 
  ggplot() +
  geom_point(aes(x = sat.service, y = sat.selection),
             position = position_jitter(width = 0.2,
                                        height = 0.2))
```

```{r}
customer |> 
  count(sat.service, sat.selection) |> 
  ggplot() +
  geom_label(aes(x = sat.service,
                 y = sat.selection,
                 label = n))
```

## Logarithmic transformation: Spending

```{r}
customer |> 
  ggplot() +
  geom_point(aes(x = online.spend, 
                 y = store.spend,
                 color = email)) +
  # https://www.color-hex.com/color-palettes/
  scale_color_manual(values = c("#8e0c14", "#2c98af"),
                     labels = c("No", "Yes")) +
  # https://en.wikipedia.org/wiki/Natural_logarithm
  ## Understanding logarithms
  ### log1p: online.spend (take 0 values)
  scale_x_continuous(transform = "log1p", 
                     breaks = c(1, 2, 5, 10, 
                                20, 50, 100, 500,
                                5000)) +
  scale_y_continuous(transform = "log1p",
                     breaks = c(1, 5, 50, 500)) +
  labs(x = "Online spending (US Dollars)",
       y = "Store physical spending (US Dollars)",
       color = "Email",
       title = "Online vs store physical spending")
```

# Summary statiscs

## Correlation

```{r}
#| message: false

correlation_matrix <- customer |> 
  select(where(is.numeric)) |> 
  correlate(use = "pairwise.complete.obs", 
            method = "pearson")

correlation_matrix |> 
  datatable()
```

```{r}
correlation_matrix |> 
  autoplot(triangular = "lower")
```
