---
title: "Comparing Groups: Statistical Tests"
date: 2024-11-06
author:
  - Juana Lopez
  - Luis Francisco Gómez 
format: 
  html:
    embed-resources: true
    number-sections: true
    toc: true
    code-fold: true
editor: visual
---

```{r}
#| message: false
library(tidyverse)
library(tidymodels)
library(DT)
```

# Import data

```{r}
#| message: false
segmentation <- read_csv(file = "../000_data/005_data_chapter5.csv")
```

# Transform data

```{r}
segmentation <- segmentation |> 
  mutate(gender = factor(x = gender, ordered = FALSE),
         kids = as.integer(x = kids),
         ownHome = factor(x = ownHome, ordered = FALSE),
         subscribe = factor(x = subscribe, ordered = FALSE),
         Segment = factor(x = Segment, ordered = FALSE))
```

# Count data 

## Segment

```{r}
count_segment <- segmentation |> 
  count(Segment) |> 
  arrange(desc(n)) |> 
  mutate(proportion = n / sum(n))

count_segment |> 
  datatable()
```

## ownHome - subscribe

```{r}
count_ownhome_subscribe <- segmentation |> 
  count(ownHome, subscribe) |> 
  pivot_wider(id_cols = subscribe, 
              names_from = ownHome, 
              values_from = n)

count_ownhome_subscribe |> 
  datatable()
```

# Statistical tests

## Chi2 proportion

```{r}
chisq_test_proportion <- segmentation |> 
  chisq_test(response = Segment,
             p = c(1/4, 1/4, 1/4, 1/4))

chisq_test_proportion |> 
  datatable()
```

## Chi2 Pearson

```{r}
chisq_test_pearson <- segmentation |> 
  chisq_test(formula = subscribe ~ ownHome,
             correct = FALSE) 
chisq_test_pearson |> 
  datatable()
```
