---
title: "Comparing groups: statistical tests"
format: 
  html:
    embed-resources: true
    toc: true
    code-fold: true
editor: visual
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(tidymodels)
```

# Import data

```{r}
#| message: false
# segmentation <- read_csv(file = "http://goo.gl/qw303p")
# If this fail use the above code
segmentation <- read_csv(file = "../000_data/005_data_chapter5.csv")
```

# Exploring data

```{r}
segmentation |> glimpse()
segmentation |> count(Segment)
```

# Chi squared test: given probabilities

```{r}
segmentation |> 
  chisq_test(response = Segment,
             p = c(1/4, 1/4, 1/4, 1/4))
```

# Chi squared test: independence

```{r}
segmentation |>
  chisq_test(formula = subscribe ~ ownHome,
             correct = FALSE)
```

# t-test: mean difference

```{r}
t_test <- t.test(formula = income ~ ownHome,
                 alternative = "two.sided",
                 mu = 0,
                 # alpha = 1 - conf.level
                 ## 0.05
                 conf.level = 0.95,
                 data = segmentation)

t_test
```

# f-test: multiple mean difference

```{r}
anova_table_2_or_more_var <- aov(formula = income ~ Segment*ownHome,
                                 data = segmentation) |> 
  anova()

anova_table_2_or_more_var
```
