---
title: "An overview of the R language"
author:
  - Norah Jones
  - Bill Gates
  - Luis Francisco Gómez
format: 
  html:
    toc: true
    number-sections: true
    code-fold: true
    embed-resources: true
---

```{r}
#| label: libraries
#| message: false

library(tidyverse)
library(skimr)
library(DT)
```

# Introduction

Insert some text

# Import

Insert some text

```{r}
#| message: false

satisfaction_data <- read_csv(file = "../000_data/002_chapter_2.csv")
```

# Inspect

Insert some text

```{r}
satisfaction_data |> 
  glimpse()
```

# Transform

Insert some text

```{r}
satisfaction_data <- satisfaction_data |> 
  mutate(Segment = factor(x = Segment, 
                          ordered = FALSE))
```

# Summarize

Insert some text

```{r}
satisfaction_data |> 
  skim()
```

# Descriptive statistics

```{r}
satisfaction_data_prod_sat <- satisfaction_data |> 
  group_by(Segment) |> 
  summarise(
    mean_prod_sat = mean(iProdSAT),
    median_prod_sat = median(iProdSAT)
  )

satisfaction_data_prod_sat |> 
  datatable(colnames = 
              c("Mean Product Satisfaction" = "mean_prod_sat",
                "Median Product Satisfaction" = "median_prod_sat")) |> 
  formatRound(columns = "Mean Product Satisfaction", 
              digits = 2)
```
